### ISSUE TITLE
redmine 2.6.0

### ISSUE THREAD

**Issue by elalemanyo** [netaustin/redmine_task_board#34]
Hi,
I will like to use your redmine plugin but I am using version 2.6.0 and your plugin is not working with this version. Are you going to do an update to support the new redmine version?

Thanks!

**Comment by AndreMiras** [comment]
What is your error, what are the steps to reproduce?

**Comment by DarkSideGeek** [comment]
On 2.6.9, I get a Server 500 error the moment that the Taskboard is activated in Settings. At this point, the project Settings is completely inaccessible. If there are any pre-steps to do, they can't be done because Settings is just toast:

```
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"services"}
  Current user: bhoule (id=3)
  Rendered plugins/redmine_dmsf/app/views/hooks/redmine_dmsf/_view_projects_form.html.erb (0.1ms)
  Rendered projects/_form.html.erb (127.9ms)
  Rendered projects/_edit.html.erb (130.1ms)
  Rendered projects/settings/_modules.html.erb (5.4ms)
  Rendered projects/settings/_members.html.erb (62.7ms)
  Rendered projects/settings/_versions.html.erb (34.2ms)
  Rendered plugins/redmine_reminder/app/views/projects/settings/_issue_categories.html.erb (3.8ms)
  Rendered projects/settings/_wiki.html.erb (2.0ms)
  Rendered projects/settings/_repositories.html.erb (1.4ms)
  Rendered projects/settings/_boards.html.erb (1.3ms)
  Rendered projects/settings/_activities.html.erb (9.3ms)
  Rendered plugins/redmine_issue_templates/app/views/issue_templates_settings/_show.html.erb (7.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_show.html.erb (4.7ms)
  Rendered plugins/redmine_custom_workflows/app/views/projects/settings/_custom_workflow.html.erb (6.7ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_state/_user_pref.html.erb (4.5ms)
  Rendered plugins/redmine_dmsf/app/views/dmsf_workflows/_main.html.erb (0.9ms)
  Rendered plugins/redmine_evm/app/views/projects/_baselines_settings.html.erb (1.2ms)
  Rendered plugins/redmine_task_board/app/views/settings/_column_manager.html.erb (24.2ms)
  Rendered plugins/redmine_task_board/app/views/settings/_project.html.erb (26.6ms)
  Rendered common/_tabs.html.erb (313.8ms)
  Rendered projects/settings.html.erb within layouts/base (314.7ms)
Completed 500 Internal Server Error in 329.3ms

ActionView::Template::Error (Mysql2::Error: Unknown column 'task_board_columns.project' in 'where clause': SELECT `task_board_columns`.* FROM `task_board_columns`  WHERE `task_board_columns`.`project` = 30 ORDER BY weight ASC):
    19:     </ul>
    20:   </div>
    21:   <div class="movable-columns" id="taskboard-columns">
    22:     <% columns.each do |column| %>
    23:       <div class="column dyn-column" data-column-id="<%= column.id.to_s %>">
    24:         <div class="input-wrapper"></div>
    25:         <h5><%= column.title %></h5>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___512531517604531211_70077397365340'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___512531517604531211_70077397365340'
  app/helpers/application_helper.rb:328:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___4486544466947945954_70077391393100'
```

Uninstalling (VERSION=0) also generates an error:

```
# rake redmine:plugins:migrate NAME=redmine_task_board VERSION=0 RAILS_ENV=production
(in /var/www/apps/redmine-2.6.9)
Migrating redmine_task_board (Redmine Task Board)...
==  CreateStatusBuckets: reverting ============================================
==  CreateStatusBuckets: reverted (0.0000s) ===================================

==  CreateTaskBoardAssignees: reverting =======================================
-- remove_index("task_board_assignees", {:column=>:assignee_id})
   -> 0.0286s
-- remove_index("task_board_assignees", {:column=>:issue_id})
   -> 0.0162s
-- drop_table("task_board_assignees")
   -> 0.0029s
==  CreateTaskBoardAssignees: reverted (0.0480s) ==============================

==  CreateTaskBoardColumns: reverting =========================================
-- remove_index("issue_statuses_task_board_columns", {:name=>"issue_statuses_task_board_columns_idx"})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'redmine.issue_statuses_task_board_columns' doesn't exist: SHOW KEYS FROM `issue_statuses_task_board_columns`/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:259:in `execute_and_free'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:407:in `indexes'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/schema_statements.rb:406:in `index_name_exists?'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/schema_statements.rb:586:in `index_name_for_remove'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/schema_statements.rb:366:in `remove_index'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:466:in `block in method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `block in say_with_time'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `say_with_time'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:458:in `method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:402:in `block (4 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:401:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:401:in `block (3 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:358:in `revert'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:400:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:399:in `block in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:389:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:528:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:777:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:777:in `ddl_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:719:in `block in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:700:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:700:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:574:in `down'
/usr/local/rvm/gems/ruby-1.9.3-p429/gems/activerecord-3.2.22/lib/active_record/migration.rb:555:in `migrate'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:469:in `migrate_plugin'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:441:in `migrate'
/var/www/apps/redmine-2.6.9/lib/redmine/plugin.rb:452:in `migrate'
/var/www/apps/redmine-2.6.9/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

So it would appear that everything stemmed from one or more custom fields not getting properly added to the DB schema?
