### ISSUE TITLE
500 Internal error - Redmine 3.0.3

### ISSUE THREAD

**Issue by gregal** [netaustin/redmine_task_board#36]
I have Redmine 3.0.3 fresh install.

Several pages present Internal error 500:
- Menu "My Task Board"
- Project > Configuration
...

**Comment by cupofnestor** [comment]
+1

Version 3.1.1
The error is below.

```
ActionView::Template::Error (undefined method `find_all_by_project_id' for #<Class:0x007f4e65843bd0>):
    24: 
    25: <div id="column_manager">
    26:   <%= render :partial => 'settings/column_manager', :locals => {
    27:         :columns => TaskBoardColumn.find_all_by_project_id(@project.id, :order => "weight ASC"),
    28:         :statuses => IssueStatus.all
    29:       }
    30:   %>
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb___3207602965417025824_69987344602080'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb___3207602965417025824_69987344602080'
  app/helpers/application_helper.rb:322:in `render_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb__3693390920449627267_69987344561360'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by morfab** [comment]
+1 , same error
my environment:
<pre>
  Redmine version                3.1.1.devel.14752
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
</pre>
